#!/bin/bash -eu

cmd_install() {
  rm -rf venv
  python3 -m venv venv
  . venv/bin/activate
  pip install -r requirements.txt
}

backup() {
  old=$1
  new=$2
  [ -e "$old" ]  && cp -f "$old" "$new" || (touch "$old" && touch "$new")
}

ipv4_sort() {
  awk -F'[./]' '{printf "%03d.%03d.%03d.%03d/%02d %s\n", $1, $2, $3, $4, $5, $0}' \
    | sort -u \
    | sed 's/^[^ ]* //'
}

diff_and_remove_same() {
  new="$1"
  old="$2"
  if diff "$old" "$new" > "$old.diff" ; then
    rm -f "$old" "$old.diff"
    echo "File $new did not change"
    true
  else
    echo "File $new changed"
  fi
}

cmd_pull_db() {
  . venv/bin/activate
  rm -f rib*.bz2
  sfx=$(date)
  backup asn.txt "asn-$sfx.txt"
  backup ipasn.lst "ipasn-$sfx.lst"
  wget -N https://ftp.ripe.net/ripe/asnames/asn.txt
  pyasn_util_download.py --latest
  pyasn_util_convert.py --single $(find . -maxdepth 1 -name "rib*.bz2" -print) ipasn.lst
  diff_and_remove_same asn.txt "asn-$sfx.txt"
  diff_and_remove_same ipasn.lst "ipasn-$sfx.lst"
}

cmd_update_ip() {
  . venv/bin/activate
  cc=${1:-RU}
  sfx=$(date)
  backup asn_${cc}.lst "asn_${cc}-$sfx.lst"
  backup ip_${cc}.lst "ip_${cc}-$sfx.lst"
  python3 ./asn-country.py ${cc}
  python3 ./ip-country.py ${cc}
  diff_and_remove_same asn_${cc}.lst "asn_${cc}-$sfx.lst"
  diff_and_remove_same ip_${cc}.lst "ip_${cc}-$sfx.lst"
}

cmd_merge_ip() {
  cat "$@" | ipv4_sort > ip_allow.lst
}

cmd_help() {
  echo "pull_db | update_ip [<CC>] | merge_ip {<CC>}+ | clean"
}

cmd_clean() {
  rm -f asn-*.txt ipasn-*.lst asn_??-*.lst ip_??-*.lst rib*.bz2 *.diff ip_allow* asn_??.lst ip_??.lst
}

if [ -z "${1:-}" ] ; then
  arg=help
else
  arg=$1
  shift
fi

"cmd_$arg" "$@"
